export const environment = {
  production: true,
  defaultauth: 'fackbackend',
  firebaseConfig: {
    apiKey: '',
    authDomain: '',
    databaseURL: '',
    projectId: '',
    storageBucket: '',
    messagingSenderId: '',
    appId: '',
    measurementId: ''
  },
  permission : {
    Add: 'Add',
    Update: 'Update',
    View: 'View',
    ChangeStatus: 'ChangeStatus',
    CancelOrder: 'CancelOrder',
    ConfirmTransaction: 'ConfirmTransaction',
    AssignTask: 'AssignTask'
  },
  pagesname : {
    Company: 'Company',
    UnitOfMeasure: 'Unit Of Measure',
    Warehouse: 'Warehouse',
    Aisles: 'Asiles',
    StorageType: 'Storage Type',
    Locations: 'Locations',
    Position: 'Position',
    PositionLevel: 'Position Level',
    PositionColumn: 'Position Column',
    PositionDirection: 'Position Direction',
    Item: 'Item',
    ItemGroup: 'Item Group',
    UserPermissions: 'User Permissions',
    Customers: 'Customers',
    Transactions: 'Transactions',
    PrintBarCode: 'Print Bar Code',
    SalesOrder: 'Sales Order',
    PalletsHistory: 'Pallets History',
    PriceList: 'Price List',
    HandlingIN: 'Handling IN',
    HandlingOut: 'Handling Out',
    Stock: 'Stock',
    WarehouseUtilization: 'Warehouse Utilization',
    Services: 'Services',
    CompaniesServices: 'Companies\' Services',
    SerialControl: 'Serial Control',
    SerialTracker: 'Serial Tracker',
    WarehousesUsers: 'Warehouses\' users',
    ItemsStatus: 'Items Status',
    ItemsConfigurations: 'Items Configurations',
    DashboardDesigner: 'Dashboard Designer',
    DashboardMain: 'Dashboard Main',
    QuickConfigurations: 'Quick Configurations',
    OperationManager: 'Operation Manager',
    ReallocationTransactions: 'Reallocation Transactions',
    NewInvoice: 'New Invoice',
    LocationMove: 'Location Move',
    CompaniesUsers: 'Companies\' users',
    ItemsMove: 'Items Move',
    TransactionSummary: 'Transaction Summary',
    GatesHandler: 'Gates Handler',
    Brand: 'Brand',
    Dock: 'Dock',
    Vendor: 'Vendor',
    PalletCategory: 'Pallet Category',
    TransactionType: 'Transaction Type',
    TransactionWay: 'Transaction Way',
    WarehouseQueue: 'Warehouse Queue',
    TruckType: 'Truck Type',
    Category: 'Category',
    MasterData: 'MasterData',
    ShiftAttribute: 'ShiftAttribute',
    ShiftSellingPrice: 'ShiftSellingPrice',
    ShiftType: 'ShiftType',
    Shift: 'Shift',
    Holiday: 'Holiday',
    UserConfiguration:"User Configuration",
    Inspection:"Inspection",
    Prepare:"Get Out",
    AssignLocation:"Assign Location",
    NewOrder:"New Order",
    Confirm:"Confirm",
    YardStock:"Yard Stock",
    PriceListUpgrade:"Price List Upgrade" 
  }
  
};
